# Build the models and save them off

In [1]:
#Import necessary packages
import psycopg2
import sys  
sys.path.append('..')

import numpy as np
import pandas as pd

from config import REDSHIFT_CONFIG
from src.features import *
from src.utils import *
from src.validation import *

reload(sys)
sys.setdefaultencoding('utf8')

from src.pitcher_class import *
from src.exploration import *

In [2]:
# Establish a connection to the redshift database
conn = create_rs_conn(config=REDSHIFT_CONFIG)
cur = conn.cursor()

In [3]:
# Create a list of the columns that we're interested in using as features
cols_of_interest = ([u'b', u's', u'on_1b', u'on_2b', u'on_3b', u'o',
                     u'stand_L', u'Not_Fastball_pb_prior', u'Not_Fastball_pbs_prior', 
                     u'Fastball_pb_prior', u'Fastball_pbs_prior', u'Not_Fastball_pc_prior', 
                     u'Not_Fastball_pcs_prior', u'Fastball_pc_prior', u'Fastball_pcs_prior', 
                     u'Not_Fastball_pg_prior', u'Not_Fastball_pgs_prior', 
                     u'Fastball_pg_prior', u'Fastball_pgs_prior', u'last_pitch_type_Fastball', 
                     u'last_pitch_type_Not_Fastball',u'last_pitch_type_not_available', 
                     u'second_last_pitch_type_Fastball',u'second_last_pitch_type_Not_Fastball',
                     u'second_last_pitch_type_not_available', u'third_last_pitch_type_Fastball',
                     u'third_last_pitch_type_Not_Fastball', u'third_last_pitch_type_not_available', 
                     u'prev_pitches_mean_start_speed', u'prev_pitches_mean_end_speed',
                     u'prev_pitches_mean_break_y', u'prev_pitches_mean_break_angle',
                     u'prev_pitches_mean_break_length', u'ingame_pitch_count', u'cur_season', u'season_pitch_count'])

In [4]:
cur.execute('''SELECT pitcher,
                    p_first_name,
                    p_last_name,
                    COUNT(*) as tot_pitch_count,
                    MAX(date) as maximum_date,
                    AVG(CASE WHEN pitch_type IN ('FA', 'FF', 'FT', 'FC', 'FS', 'SI', 'SF') THEN 1.0
                        ELSE 0.0 END) as fastball_perc
                FROM 
                    all_pitch_data
                GROUP BY pitcher, p_first_name, p_last_name
                HAVING count(*) >= %d AND 
                MAX(date) > '%s' AND
                AVG(CASE WHEN pitch_type IN ('FA', 'FF', 'FT', 'FC', 'FS', 'SI', 'SF') THEN 1.0
                        ELSE 0.0 END) BETWEEN 0.4 AND 0.6
                ORDER BY pitcher''' % (3000, '2015-01-01'))

In [5]:
rows = cur.fetchall()
header = [colnames[0] for colnames in cur.description]
pitcher_df = pd.DataFrame(rows)
pitcher_df.columns = header
pitcher_df

,pitcher,p_first_name,p_last_name,tot_pitch_count,maximum_date,fastball_perc
0,115629,LaTroy,Hawkins,5918,2015-07-20,0.6
1,136600,Bruce,Chen,12153,2015-05-15,0.4
2,150274,Joe,Nathan,6239,2015-04-06,0.5
3,150302,Jason,Marquis,13759,2015-05-25,0.5
4,150359,A.J.,Burnett,25345,2015-07-20,0.6
5,276351,Jason,Grilli,6146,2015-07-11,0.6
6,276542,Joaquin,Benoit,6843,2015-07-20,0.5
7,279571,Matt,Belisle,7676,2015-06-25,0.6
8,279824,Mark,Buehrle,24295,2015-07-21,0.6
9,282332,CC,Sabathia,24873,2015-07-19,0.5
10,285064,Ryan,Vogelsong,13055,2015-07-20,0.5
11,329092,Randy,Choate,3764,2015-07-19,0.6
12,346793,Jeremy,Affeldt,7099,2015-06-25,0.6
13,346798,Kyle,Lohse,20953,2015-07-12,0.5
14,407845,Fernando,Rodney,8192,2015-07-21,0.6
15,407890,Colby,Lewis,13420,2015-07-18,0.5
16,408061,Francisco,Rodriguez,8227,2015-07-18,0.5
17,421685,Aaron,Harang,21147,2015-07-01,0.6
18,424144,Oliver,Perez,8552,2015-07-20,0.6
19,425386,Jeremy,Guthrie,24366,2015-07-18,0.5
20,425492,Ryan,Madson,5355,2015-07-21,0.6
21,425626,Chris,Capuano,10860,2015-07-07,0.5
22,425657,Javier,Lopez,5172,2015-07-19,0.6
23,425794,Adam,Wainwright,20137,2015-04-25,0.6
24,425840,Neal,Cotts,3550,2015-07-21,0.5
25,425844,Zack,Greinke,24877,2015-07-19,0.6
26,429719,Edwin,Jackson,22384,2015-07-11,0.6
27,429722,Ervin,Santana,22319,2015-07-17,0.5
28,429781,Kevin,Correia,18195,2015-07-04,0.4
29,430589,Chad,Qualls,6765,2015-07-19,0.6
...,...,...,...,...,...,...
197,543506,Brandon,Maurer,3321,2015-07-20,0.4
198,543521,Collin,McHugh,5224,2015-07-17,0.4
199,543548,Tommy,Milone,9212,2015-07-19,0.6
200,543699,Tanner,Roark,4840,2015-07-21,0.6
201,544931,Stephen,Strasburg,11213,2015-07-04,0.6
202,545333,Trevor,Bauer,5036,2015-07-17,0.6
203,545404,Brandon,Beachy,4635,2015-07-20,0.6
204,547749,Junichi,Tazawa,3997,2015-07-21,0.6
205,570649,Yordano,Ventura,4847,2015-07-20,0.6
206,571521,Rex,Brothers,4164,2015-07-21,0.6
207,571578,Patrick,Corbin,4907,2015-07-19,0.6
208,571666,Mike,Fiers,5528,2015-07-17,0.6
209,571800,Drew,Hutchison,5798,2015-07-17,0.6
210,571901,Aaron,Loup,3108,2015-07-18,0.6
211,572070,Garrett,Richards,8089,2015-07-18,0.6
212,572971,Dallas,Keuchel,9016,2015-07-19,0.6
213,573064,Vidal,Nuno,3321,2015-07-19,0.4
214,573109,A.J.,Ramos,3235,2015-07-21,0.5
215,573185,Dan,Straily,4185,2015-07-08,0.5
216,592102,Cody,Allen,3554,2015-07-19,0.6
217,592332,Kevin,Gausman,3306,2015-07-07,0.6
218,592665,Addison,Reed,3676,2015-06-20,0.6
219,593372,Carlos,Martinez,3849,2015-07-19,0.6
220,594798,Jacob,deGrom,4025,2015-07-21,0.6
221,605228,Jose,Fernandez,3649,2015-07-17,0.5
222,606273,Roenis,Elias,3868,2015-07-02,0.5
223,607259,Nick,Martinez,4078,2015-07-20,0.6
224,612672,Wei-Yin,Chen,10296,2015-07-21,0.6
225,622072,Alex,Wood,5799,2015-07-21,0.6
226,628333,Odrisamer,Despaigne,3026,2015-07-21,0.6

In [35]:
def randomly_sample_pitchers3(cursor, num_pitchers = 5, min_pitch_count = 600, min_date = '2015-01-01', seed_num = None):
    '''Takes a random sample of pitchers from the db represented by "cursor" and returns a Pandas DF with
    the specified number ofpitchers who have thrown at least "min_pitch_count" pitches
    Input:
        cursor: DB handle
        num_pitchers: The number of pitchers whose data you want returned
        min_pitch_count: Minimum number of pitches a pitcher must have thrown in order to be considered in the 
            random sampling
        seed_num: If you want to be able to replicated the results, set a seed
    Output: Pandas DF containing pitcher ids, the number of pitches they've thrown and their max pitch date'''
    cur = cursor
    
    #Get all pitchers meeting the min pitches criterion
    get_pitchers_query = '''SELECT pitcher,
                    p_first_name,
                    p_last_name,
                    COUNT(*) as tot_pitch_count,
                    MAX(date) as maximum_date,
                    AVG(CASE WHEN pitch_type IN ('FA', 'FF', 'FT', 'FC', 'FS', 'SI', 'SF') THEN 1.00
                        ELSE 0.00 END) as fastball_perc,
                    SUM(CASE WHEN pitch_type IN ('FA', 'FF', 'FT', 'FC', 'FS', 'SI', 'SF') THEN 1.0
                        ELSE 0.0 END) as num_fastballs,
                    SUM(CASE WHEN pitch_type NOT IN ('FA', 'FF', 'FT', 'FC', 'FS', 'SI', 'SF') THEN 1.0
                        ELSE 0.0 END) as num_not_fastballs
                FROM 
                    all_pitch_data
                GROUP BY pitcher, p_first_name, p_last_name
                HAVING count(*) >= %d AND 
                MAX(date) > '%s' AND
                AVG(CASE WHEN pitch_type IN ('FA', 'FF', 'FT', 'FC', 'FS', 'SI', 'SF') THEN 1.00
                        ELSE 0.00 END) BETWEEN 0.40 AND 0.60
                ORDER BY pitcher''' % (min_pitch_count, min_date)
    cur.execute(get_pitchers_query)
    
    #Get all the pitcher ids and sample from them
    if seed_num is not None:
        seed(seed_num)
    
    rows = cur.fetchall()
    header = [colnames[0] for colnames in cur.description]
    pitcher_df = pd.DataFrame(rows)
    pitcher_df.columns = header
    
    pitcher_id_sample = sample(pitcher_df['pitcher'].values, num_pitchers)
    
    pitcher_df = pitcher_df[pitcher_df['pitcher'].isin(pitcher_id_sample)]
    
    return pitcher_df

In [6]:
pitchers = randomly_sample_pitchers3(cur, min_pitch_count=2000, seed_num=35)

In [7]:
pitchers

,pitcher,p_first_name,p_last_name,tot_pitch_count,maximum_date,fastball_perc
37,448306,James,Shields,27096,2015-07-17,0.58
71,476454,Dellin,Betances,2365,2015-07-21,0.51
97,518716,Dillon,Gee,10567,2015-06-14,0.57
112,543359,Dan,Jennings,2218,2015-07-21,0.58
125,573185,Dan,Straily,4185,2015-07-08,0.58

In [8]:
pitcher_list = pitchers['pitcher'].values

In [9]:
tester = Pitcher(pitcher_list[0], cur)

In [10]:
best_date = tester.find_optimal_date_splits()

In [11]:
best_date

'2010-09-15'

In [12]:
tester.subset_data_by_date(min_date = best_date)

In [13]:
tester.split_test_train()

In [14]:
tester.run_classifiers()

In [15]:
tester.classifiers

{'rf': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=3, max_features='auto', max_leaf_nodes=None,
             min_samples_leaf=7, min_samples_split=6,
             min_weight_fraction_leaf=0.0, n_estimators=350, n_jobs=1,
             oob_score=False, random_state=None, verbose=0,
             warm_start=False)}

In [16]:
tester.predict(tester.modeling_dict['test_data'])

0           Fastball
1           Fastball
2           Fastball
3           Fastball
4           Fastball
5           Fastball
6           Fastball
7           Fastball
8           Fastball
9           Fastball
10          Fastball
11          Fastball
12          Fastball
13      Not_Fastball
14          Fastball
15      Not_Fastball
16          Fastball
17          Fastball
18          Fastball
19          Fastball
20          Fastball
21          Fastball
22          Fastball
23          Fastball
24      Not_Fastball
25      Not_Fastball
26      Not_Fastball
27      Not_Fastball
28          Fastball
29          Fastball
            ...
1743        Fastball
1744        Fastball
1745        Fastball
1746        Fastball
1747        Fastball
1748        Fastball
1749    Not_Fastball
1750    Not_Fastball
1751    Not_Fastball
1752        Fastball
1753    Not_Fastball
1754    Not_Fastball
1755    Not_Fastball
1756        Fastball
1757        Fastball
1758    Not_Fastball
1759    Not_Fastball
1760    Not_Fastball
1761    Not_Fastball
1762        Fastball
1763        Fastball
1764        Fastball
1765        Fastball
1766        Fastball
1767        Fastball
1768        Fastball
1769        Fastball
1770        Fastball
1771        Fastball
1772        Fastball
dtype: object

In [17]:
test_data = tester.modeling_dict['test_data']

In [18]:
tester.prepare_for_pickle()

In [19]:
tester.predict(test_data)

0           Fastball
1           Fastball
2           Fastball
3           Fastball
4           Fastball
5           Fastball
6           Fastball
7           Fastball
8           Fastball
9           Fastball
10          Fastball
11          Fastball
12          Fastball
13      Not_Fastball
14          Fastball
15      Not_Fastball
16          Fastball
17          Fastball
18          Fastball
19          Fastball
20          Fastball
21          Fastball
22          Fastball
23          Fastball
24      Not_Fastball
25      Not_Fastball
26      Not_Fastball
27      Not_Fastball
28          Fastball
29          Fastball
            ...
1743        Fastball
1744        Fastball
1745        Fastball
1746        Fastball
1747        Fastball
1748        Fastball
1749    Not_Fastball
1750    Not_Fastball
1751    Not_Fastball
1752        Fastball
1753    Not_Fastball
1754    Not_Fastball
1755    Not_Fastball
1756        Fastball
1757        Fastball
1758    Not_Fastball
1759    Not_Fastball
1760    Not_Fastball
1761    Not_Fastball
1762        Fastball
1763        Fastball
1764        Fastball
1765        Fastball
1766        Fastball
1767        Fastball
1768        Fastball
1769        Fastball
1770        Fastball
1771        Fastball
1772        Fastball
dtype: object

### Get pitcher ids for the guys pitching tomorrow night

In [28]:
cur.execute('''SELECT 
                    count(*) as num_pitches,
                    MAX(date) as latest_pitch_date,
                    p_first_name,
                    p_last_name,
                    pitcher
                FROM all_pitch_data
                WHERE p_first_name IN ('Williams', 'Colin', 'Cole', 'Scott', 'Matt', 'Carlos', 'Andrew') AND
                p_last_name IN ('Perez', 'Rea', 'Hamels', 'Kazmir', 'Garza', 'Rodon', 'Heaney')
                GROUP BY p_first_name, p_last_name, pitcher;''')
rows = cur.fetchall()
header = [colnames[0] for colnames in cur.description]
pitcher_df = pd.DataFrame(rows)
pitcher_df.columns = header
pitcher_df

   num_pitches latest_pitch_date p_first_name p_last_name  pitcher
0        21671        2015-07-21         Matt       Garza   490063
1        26067        2015-07-19         Cole      Hamels   430935
2        16327        2015-07-18        Scott      Kazmir   431148
3          940        2015-07-20       Andrew      Heaney   571760
4         1331        2015-07-21       Carlos       Rodon   607074
5          804        2015-06-26     Williams       Perez   554234

In [29]:
pitcher_list = np.append(pitcher_list, pitcher_df['pitcher'].values)
pitcher_list

array([448306, 476454, 518716, 543359, 573185, 490063, 430935, 431148,
       571760, 607074, 554234], dtype=int64)

In [ ]:
for pitcher in pitcher_list:

In [68]:
pitcher = pitcher_list[0]

In [30]:
accuracies = {}
erros = []

for pitcher in pitcher_list[:2]:
    
    try:
        print 'starting pitcher:', pitcher
        test = Pitcher(pitcher_id = pitcher, redshift_cursor = cur)
        #test dates with Jason's code
        #test.subset_data_by_date(max_date = '2014-01-01')
        print test.pitch_type_by_year()
        test.split_test_train()
        print 'baseline acc:', test.baseline_accuracy
        test.run_classifiers()
        accuracies[pitcher] = {}
        accuracies[pitcher]['improvement'] = test.acc_over_most_common
        accuracies[pitcher]['rel_improvement'] = test.acc_over_most_common / (1 - test.baseline_accuracy)
        accuracies[pitcher]['baseline'] = test.baseline_accuracy
        print "\n"
        
    except:
        print "something went wrong with", pitcher, "\n"
        errors.append(pitcher)

In [31]:
accuracies

{448306: {'baseline': 0.605,
  'improvement': 0.058742690058479541,
  'rel_improvement': 0.14871567103412542},
 476454: {'baseline': 0.502,
  'improvement': 0.10274308300395252,
  'rel_improvement': 0.20631141165452313}}

To do:
* method in pitcher class to output data in the way Jason wants it
* loop to go through all pitchers and build models and save them
* Find pitcher ids of Cole Hamels, Scott Kazmir, and Matt Garza
* Function to train models on all of the data (not just the train)

In [ ]:
tester =